import { FileVideo, Github, Upload } from "lucide-react";

import { Button } from "./components/ui/button";
import { Label } from "./components/ui/label";
import { Separator } from "./components/ui/separator";
import { Textarea } from "./components/ui/textarea";

export function App() {
  return (
    <div className="flex flex-col min-h-screen">
      <div className="px-6 py-3 flex items-center justify-between border-b">
        <h1 className="font-bold text-xl">video.ai</h1>

        <div className="flex items-center gap-3">
          <span className="text-sm text-muted-foreground">
            Developed by
            <a
              className="font-bold hover:underline ml-1"
              href="https://github.com/felipefa"
            >
              @felipefa
            </a>
          </span>

          <Separator className="h-6" orientation="vertical" />

          <a href="https://github.com/felipefa/video-ai-web">
            <Button variant="outline">
              <Github className="h-4 w-4 mr-2" />
              GitHub
            </Button>
          </a>
        </div>
      </div>

      <main className="flex flex-1 gap-6 p-6">
        <div className="flex flex-col flex-1 gap-4">
          <div className="flex-1 gap-4 grid grid-rows-2">
            <Textarea
              className="resize-none p-4 leading-relaxed"
              placeholder="Enter the prompt for the AI..."
            />
            <Textarea
              className="resize-none p-4 leading-relaxed"
              placeholder="Result generated by the AI..."
              readOnly
            />
          </div>

          <p className="text-sm text-muted-foreground">
            Pro tip: you can use the{" "}
            <code className="text-primary">{"{transcription}"}</code> variable
            in your prompt to add the content of the your video there
          </p>
        </div>

        <aside className="w-80 space-y-6">
          <form className="space-y-6">
            <label
              htmlFor="video"
              className="border flex rounded-md aspect-video cursor-pointer border-da\ text-sm flex-col gap-2 items-center justify-center text-muted-foreground hover:bg-primary/5"
            >
              <FileVideo className="h-4 w-4" />
              Select a video
            </label>

            <input
              type="file"
              id="video"
              accept="video/mp4"
              className="sr-only"
            />

            <Separator />

            <div className="space-y-1">
              <Label htmlFor="transcription_prompt">Transcription Prompt</Label>
              <Textarea
                id="transcription_prompt"
                className="min-2-20 leading-relaxed"
                placeholder="Enter keywords mentioned in the video separated by comma (,)"
              />
            </div>

            <Button className="w-full" type="submit">
              Upload video
              <Upload className="w-4 h-4 ml-2" />
            </Button>
          </form>
        </aside>
      </main>
    </div>
  );
}
